### ISSUE TITLE
Where are the data (rules) saved ?

### ISSUE THREAD

**Issue by blackloaderz** [canisbos/Quickstyle#1]
Hello,
Does anyone knows where the data (the css rules) are written ?
Since Apple have updated the policy and removed all the not allowed extensions, I've lost QuickStyle and my rules. I'm looking to restore them with a backup, but I don't know where to got them back.
Cheers

**Comment by canisbos** [comment]
Hi,

Quickstyle stores its CSS in the extension's `localStorage`, which Safari writes to the following file:

> ~/Library/Safari/LocalStorage/safari-extension_com.canisbos.rightsizer-0000000000_0.localstorage

Although these .localStorage files are sqlite databases and thus readable using sqlite, the actual values (CSS styles) are stored as binary data, and thus not easy to parse.

There is a much easier way to get at Quickstyle stylesheets for the purpose of copying them, but it does unfortunately involve visiting each site whose Quickstyle stylesheet you want to save. Basically, you visit the site, open Safari's DOM inspector, expand the `<head>` element, and look toward the bottom for the `<style id="QuickstyleCSS">` element. Then you can just expand this element and copy the rules right out of it.

Of course, in order to be able to do that, you'll have to actually run Quickstyle. You should be able to do so by following the [instructions on this page](https://sixcolors.com/post/2018/09/give-new-life-to-old-extensions-in-safari-12/) or others you can find by googling.

However, I do not know whether, after re-enabling Quickstyle in this way, the extension will use the same .localStorage file that was created when the extension was running normally. Good luck.

**Comment by blackloaderz** [comment]
Thanks for your reply!! You were right.
I was able to recover a few things with the backed up localstorage file.
If you feel like making this extension available in the AppStore, I would be glad to pay for it.
Have a nice day!
